<?php
/**
 * Title: FAQ Accordion
 * Slug: airo-wp/faq/accordion-faq
 * Categories: airo-wp-faq
 * Description: A frequently asked questions section using the Accordion block
 * Keywords: faq, accordion, questions, help, support
 */

defined( 'ABSPATH' ) || exit;

return array(
	'title'      => __( 'FAQ Accordion', 'airo-wp' ),
	'categories' => array( 'airo-wp-faq' ),
	'viewportWidth' => 1200,
	'content'    => '<!-- wp:airo-wp/section {"style":{"spacing":{"padding":{"top":"var:preset|spacing|80","bottom":"var:preset|spacing|80","left":"var:preset|spacing|30","right":"var:preset|spacing|30"}}},"metadata":{"categories":["airo-wp-faq"],"patternName":"airo-wp/faq/faq-accordion-animated","name":"FAQ Accordion Animated"}} -->
<div class="wp-block-airo-wp-section alignfull airo-wp-stack" style="padding-top:var(--wp--preset--spacing--80);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--80);padding-left:var(--wp--preset--spacing--30)"><div class="airo-wp-stack__inner" style="max-width:var(--wp--style--global--content-size, 1140px);margin-left:auto;margin-right:auto"><!-- wp:airo-wp/grid {"desktopColumns":2,"style":{"spacing":{"blockGap":"var:preset|spacing|60","padding":{"top":"0","bottom":"0","left":"0","right":"0"}}},"alignItems":"start"} -->
<div class="wp-block-airo-wp-grid alignfull airo-wp-grid airo-wp-grid-cols-2 airo-wp-grid-cols-tablet-2 airo-wp-grid-cols-mobile-1 airo-wp-no-width-constraint" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0"><div class="airo-wp-grid__inner" style="display:grid;grid-template-columns:repeat(2, 1fr);align-items:start;row-gap:var(--wp--preset--spacing--60);column-gap:var(--wp--preset--spacing--60)"><!-- wp:airo-wp/section {"style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"}}},"dsgoAnimationEnabled":true,"dsgoEntranceAnimation":"fadeInLeft"} -->
<div class="wp-block-airo-wp-section alignfull airo-wp-stack has-airo-wp-animation airo-wp-animation-fadeInLeft" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0" data-airo-wp-animation-enabled="true" data-airo-wp-entrance-animation="fadeInLeft"><div class="airo-wp-stack__inner" style="max-width:var(--wp--style--global--content-size, 1140px);margin-left:auto;margin-right:auto"><!-- wp:paragraph {"style":{"typography":{"textTransform":"uppercase","letterSpacing":"3px"},"color":{"text":"#6366f1"}},"fontSize":"small"} -->
<p class="has-text-color has-small-font-size" style="color:#6366f1;letter-spacing:3px;text-transform:uppercase">FAQ</p>
<!-- /wp:paragraph -->

<!-- wp:heading {"style":{"typography":{"fontStyle":"normal","fontWeight":"700"},"spacing":{"margin":{"top":"var:preset|spacing|10"}}},"fontSize":"x-large"} -->
<h2 class="wp-block-heading has-x-large-font-size" style="margin-top:var(--wp--preset--spacing--10);font-style:normal;font-weight:700">Frequently Asked Questions</h2>
<!-- /wp:heading -->

<!-- wp:paragraph {"style":{"spacing":{"margin":{"top":"var:preset|spacing|20"}},"color":{"text":"#64748b"}},"fontSize":"medium"} -->
<p class="has-text-color has-medium-font-size" style="color:#64748b;margin-top:var(--wp--preset--spacing--20)">Can\'t find what you\'re looking for? Feel free to contact our support team for personalized assistance.</p>
<!-- /wp:paragraph -->

<!-- wp:airo-wp/icon-button {"url":"#","icon":"envelope","iconGap":"8px","className":"has-text-color has-background","style":{"spacing":{"padding":{"top":"var:preset|spacing|20","bottom":"var:preset|spacing|20","left":"var:preset|spacing|30","right":"var:preset|spacing|30"},"margin":{"top":"var:preset|spacing|30"}},"border":{"radius":"8px"},"color":{"background":"#6366f1","text":"#ffffff"}}} -->
<div class="wp-block-airo-wp-icon-button airo-wp-justify airo-wp-justify--left has-text-color has-background" style="margin-top:var(--wp--preset--spacing--30)"><a class="airo-wp-icon-button wp-block-button wp-block-button__link wp-element-button has-text-color has-background airo-wp-icon-button--has-icon" style="border-radius:8px;color:#ffffff;background-color:#6366f1;gap:8px;padding-top:var(--wp--preset--spacing--20);padding-right:var(--wp--preset--spacing--30);padding-bottom:var(--wp--preset--spacing--20);padding-left:var(--wp--preset--spacing--30)" href="#" target="_self"><span class="airo-wp-icon-button__icon airo-wp-lazy-icon" data-icon-name="envelope"></span><span class="airo-wp-icon-button__text">Contact Support</span></a></div>
<!-- /wp:airo-wp/icon-button --></div></div>
<!-- /wp:airo-wp/section -->

<!-- wp:airo-wp/section {"style":{"spacing":{"padding":{"top":"0","bottom":"0","left":"0","right":"0"}}},"dsgoAnimationEnabled":true,"dsgoEntranceAnimation":"fadeInRight"} -->
<div class="wp-block-airo-wp-section alignfull airo-wp-stack has-airo-wp-animation airo-wp-animation-fadeInRight" style="padding-top:0;padding-right:0;padding-bottom:0;padding-left:0" data-airo-wp-animation-enabled="true" data-airo-wp-entrance-animation="fadeInRight"><div class="airo-wp-stack__inner" style="max-width:var(--wp--style--global--content-size, 1140px);margin-left:auto;margin-right:auto"><!-- wp:airo-wp/accordion {"style":{"spacing":{"blockGap":"var:preset|spacing|15"}}} -->
<div class="wp-block-airo-wp-accordion airo-wp-accordion airo-wp-accordion--icon-right airo-wp-accordion--border-between" style="--airo-wp-accordion-open-bg:;--airo-wp-accordion-open-text:;--airo-wp-accordion-hover-bg:;--airo-wp-accordion-hover-text:;--airo-wp-accordion-gap:0.5rem" data-allow-multiple="false" data-icon-style="chevron"><div class="airo-wp-accordion__items"><!-- wp:airo-wp/accordion-item {"title":"How do I get started?","isOpen":true,"uniqueId":"faq-anim-001","backgroundColor":"base-2","style":{"border":{"radius":"12px"},"spacing":{"padding":{"top":"var:preset|spacing|20","bottom":"var:preset|spacing|20","left":"var:preset|spacing|25","right":"var:preset|spacing|25"}}}} -->
<div class="wp-block-airo-wp-accordion-item airo-wp-accordion-item airo-wp-accordion-item--open has-base-2-background-color has-background" data-initially-open="true" style="border-radius:12px;padding-top:var(--wp--preset--spacing--20);padding-right:var(--wp--preset--spacing--25);padding-bottom:var(--wp--preset--spacing--20);padding-left:var(--wp--preset--spacing--25)"><div class="airo-wp-accordion-item__header"><button type="button" class="airo-wp-accordion-item__trigger airo-wp-accordion-item__trigger--icon-right" aria-expanded="true" aria-controls="faq-anim-001-panel" id="faq-anim-001-header"><span class="airo-wp-accordion-item__title">How do I get started?</span><span class="airo-wp-accordion-item__icon" aria-hidden="true"><svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M4.427 6.427l3.396 3.396a.25.25 0 00.354 0l3.396-3.396A.25.25 0 0011.396 6H4.604a.25.25 0 00-.177.427z"></path></svg></span></button></div><div class="airo-wp-accordion-item__panel" role="region" aria-labelledby="faq-anim-001-header" id="faq-anim-001-panel"><div class="airo-wp-accordion-item__content"><!-- wp:paragraph {"style":{"color":{"text":"#64748b"}}} -->
<p class="has-text-color" style="color:#64748b">Getting started is easy! Simply create an account, choose your plan, and follow our quick setup wizard. You\'ll be up and running in less than 5 minutes.</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:airo-wp/accordion-item -->

<!-- wp:airo-wp/accordion-item {"title":"What payment methods do you accept?","uniqueId":"faq-anim-002","backgroundColor":"base-2","style":{"border":{"radius":"12px"},"spacing":{"padding":{"top":"var:preset|spacing|20","bottom":"var:preset|spacing|20","left":"var:preset|spacing|25","right":"var:preset|spacing|25"}}}} -->
<div class="wp-block-airo-wp-accordion-item airo-wp-accordion-item airo-wp-accordion-item--closed has-base-2-background-color has-background" data-initially-open="false" style="border-radius:12px;padding-top:var(--wp--preset--spacing--20);padding-right:var(--wp--preset--spacing--25);padding-bottom:var(--wp--preset--spacing--20);padding-left:var(--wp--preset--spacing--25)"><div class="airo-wp-accordion-item__header"><button type="button" class="airo-wp-accordion-item__trigger airo-wp-accordion-item__trigger--icon-right" aria-expanded="false" aria-controls="faq-anim-002-panel" id="faq-anim-002-header"><span class="airo-wp-accordion-item__title">What payment methods do you accept?</span><span class="airo-wp-accordion-item__icon" aria-hidden="true"><svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M4.427 6.427l3.396 3.396a.25.25 0 00.354 0l3.396-3.396A.25.25 0 0011.396 6H4.604a.25.25 0 00-.177.427z"></path></svg></span></button></div><div class="airo-wp-accordion-item__panel" role="region" aria-labelledby="faq-anim-002-header" id="faq-anim-002-panel" hidden><div class="airo-wp-accordion-item__content"><!-- wp:paragraph {"style":{"color":{"text":"#64748b"}}} -->
<p class="has-text-color" style="color:#64748b">We accept all major credit cards (Visa, MasterCard, American Express), PayPal, and bank transfers. Enterprise customers can also pay via invoice.</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:airo-wp/accordion-item -->

<!-- wp:airo-wp/accordion-item {"title":"Can I cancel my subscription anytime?","uniqueId":"faq-anim-003","backgroundColor":"base-2","style":{"border":{"radius":"12px"},"spacing":{"padding":{"top":"var:preset|spacing|20","bottom":"var:preset|spacing|20","left":"var:preset|spacing|25","right":"var:preset|spacing|25"}}}} -->
<div class="wp-block-airo-wp-accordion-item airo-wp-accordion-item airo-wp-accordion-item--closed has-base-2-background-color has-background" data-initially-open="false" style="border-radius:12px;padding-top:var(--wp--preset--spacing--20);padding-right:var(--wp--preset--spacing--25);padding-bottom:var(--wp--preset--spacing--20);padding-left:var(--wp--preset--spacing--25)"><div class="airo-wp-accordion-item__header"><button type="button" class="airo-wp-accordion-item__trigger airo-wp-accordion-item__trigger--icon-right" aria-expanded="false" aria-controls="faq-anim-003-panel" id="faq-anim-003-header"><span class="airo-wp-accordion-item__title">Can I cancel my subscription anytime?</span><span class="airo-wp-accordion-item__icon" aria-hidden="true"><svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M4.427 6.427l3.396 3.396a.25.25 0 00.354 0l3.396-3.396A.25.25 0 0011.396 6H4.604a.25.25 0 00-.177.427z"></path></svg></span></button></div><div class="airo-wp-accordion-item__panel" role="region" aria-labelledby="faq-anim-003-header" id="faq-anim-003-panel" hidden><div class="airo-wp-accordion-item__content"><!-- wp:paragraph {"style":{"color":{"text":"#64748b"}}} -->
<p class="has-text-color" style="color:#64748b">Yes, absolutely! You can cancel your subscription at any time from your account settings. There are no cancellation fees, and you\'ll retain access until the end of your billing period.</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:airo-wp/accordion-item -->

<!-- wp:airo-wp/accordion-item {"title":"Do you offer refunds?","uniqueId":"faq-anim-004","backgroundColor":"base-2","style":{"border":{"radius":"12px"},"spacing":{"padding":{"top":"var:preset|spacing|20","bottom":"var:preset|spacing|20","left":"var:preset|spacing|25","right":"var:preset|spacing|25"}}}} -->
<div class="wp-block-airo-wp-accordion-item airo-wp-accordion-item airo-wp-accordion-item--closed has-base-2-background-color has-background" data-initially-open="false" style="border-radius:12px;padding-top:var(--wp--preset--spacing--20);padding-right:var(--wp--preset--spacing--25);padding-bottom:var(--wp--preset--spacing--20);padding-left:var(--wp--preset--spacing--25)"><div class="airo-wp-accordion-item__header"><button type="button" class="airo-wp-accordion-item__trigger airo-wp-accordion-item__trigger--icon-right" aria-expanded="false" aria-controls="faq-anim-004-panel" id="faq-anim-004-header"><span class="airo-wp-accordion-item__title">Do you offer refunds?</span><span class="airo-wp-accordion-item__icon" aria-hidden="true"><svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M4.427 6.427l3.396 3.396a.25.25 0 00.354 0l3.396-3.396A.25.25 0 0011.396 6H4.604a.25.25 0 00-.177.427z"></path></svg></span></button></div><div class="airo-wp-accordion-item__panel" role="region" aria-labelledby="faq-anim-004-header" id="faq-anim-004-panel" hidden><div class="airo-wp-accordion-item__content"><!-- wp:paragraph {"style":{"color":{"text":"#64748b"}}} -->
<p class="has-text-color" style="color:#64748b">We offer a 30-day money-back guarantee on all plans. If you\'re not satisfied, contact our support team within 30 days for a full refund, no questions asked.</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:airo-wp/accordion-item -->

<!-- wp:airo-wp/accordion-item {"title":"Is my data secure?","uniqueId":"faq-anim-005","backgroundColor":"base-2","style":{"border":{"radius":"12px"},"spacing":{"padding":{"top":"var:preset|spacing|20","bottom":"var:preset|spacing|20","left":"var:preset|spacing|25","right":"var:preset|spacing|25"}}}} -->
<div class="wp-block-airo-wp-accordion-item airo-wp-accordion-item airo-wp-accordion-item--closed has-base-2-background-color has-background" data-initially-open="false" style="border-radius:12px;padding-top:var(--wp--preset--spacing--20);padding-right:var(--wp--preset--spacing--25);padding-bottom:var(--wp--preset--spacing--20);padding-left:var(--wp--preset--spacing--25)"><div class="airo-wp-accordion-item__header"><button type="button" class="airo-wp-accordion-item__trigger airo-wp-accordion-item__trigger--icon-right" aria-expanded="false" aria-controls="faq-anim-005-panel" id="faq-anim-005-header"><span class="airo-wp-accordion-item__title">Is my data secure?</span><span class="airo-wp-accordion-item__icon" aria-hidden="true"><svg width="16" height="16" viewBox="0 0 16 16" fill="currentColor"><path d="M4.427 6.427l3.396 3.396a.25.25 0 00.354 0l3.396-3.396A.25.25 0 0011.396 6H4.604a.25.25 0 00-.177.427z"></path></svg></span></button></div><div class="airo-wp-accordion-item__panel" role="region" aria-labelledby="faq-anim-005-header" id="faq-anim-005-panel" hidden><div class="airo-wp-accordion-item__content"><!-- wp:paragraph {"style":{"color":{"text":"#64748b"}}} -->
<p class="has-text-color" style="color:#64748b">Security is our top priority. We use industry-standard encryption, regular security audits, and are SOC 2 Type II certified. Your data is stored in secure, geo-redundant data centers.</p>
<!-- /wp:paragraph --></div></div></div>
<!-- /wp:airo-wp/accordion-item --></div></div>
<!-- /wp:airo-wp/accordion --></div></div>
<!-- /wp:airo-wp/section --></div></div>
<!-- /wp:airo-wp/grid --></div></div>
<!-- /wp:airo-wp/section -->',
);
