<?php
/**
 * Auto-generated by dsg-sync — do not edit.
 *
 * @package airo-wp
 */

declare(strict_types=1);

defined( 'ABSPATH' ) || exit;

require_once __DIR__ . '/block-support-routing.php';
require_once __DIR__ . '/field-render-helpers.php';
require_once __DIR__ . '/helpers.php';
