/**
 * Tabs Block - Save Component
 *
 * Renders tab navigation and panels on frontend
 */

import { useBlockProps, useInnerBlocksProps } from '@wordpress/block-editor';
import { convertColorToCSSVar } from '../../utils/convert-preset-to-css-var';

export default function Save({ attributes }) {
	const {
		uniqueId,
		orientation,
		activeTab,
		alignment,
		mobileBreakpoint,
		mobileMode,
		enableDeepLinking,
		gap,
		tabStyle,
		tabColor,
		tabBackgroundColor,
		tabContentBackgroundColor,
		activeTabColor,
		activeTabBackgroundColor,
		tabBorderColor,
		tabHoverColor,
		tabHoverBackgroundColor,
		showNavBorder,
	} = attributes;

	const blockProps = useBlockProps.save({
		className: `airo-wp-tabs airo-wp-tabs-${uniqueId} airo-wp-tabs--${orientation} airo-wp-tabs--${tabStyle} airo-wp-tabs--align-${alignment}${showNavBorder ? ' airo-wp-tabs--show-nav-border' : ''}`,
		'data-active-tab': activeTab,
		'data-mobile-breakpoint': mobileBreakpoint,
		'data-mobile-mode': mobileMode,
		'data-deep-linking': enableDeepLinking ? 'true' : 'false',
		style: {
			'--airo-wp-tabs-gap': gap,
			...(tabColor && {
				'--airo-wp-tab-color': convertColorToCSSVar(tabColor),
			}),
			...(tabBackgroundColor && {
				'--airo-wp-tab-bg': convertColorToCSSVar(tabBackgroundColor),
			}),
			...(tabContentBackgroundColor && {
				'--airo-wp-tab-content-bg': convertColorToCSSVar(
					tabContentBackgroundColor
				),
			}),
			...(activeTabColor && {
				'--airo-wp-tab-color-active': convertColorToCSSVar(activeTabColor),
			}),
			...(activeTabBackgroundColor && {
				'--airo-wp-tab-bg-active': convertColorToCSSVar(
					activeTabBackgroundColor
				),
			}),
			...(tabBorderColor && {
				'--airo-wp-tab-border-color': convertColorToCSSVar(tabBorderColor),
			}),
			...(tabHoverColor && {
				'--airo-wp-tab-color-hover': convertColorToCSSVar(tabHoverColor),
			}),
			...(tabHoverBackgroundColor && {
				'--airo-wp-tab-bg-hover': convertColorToCSSVar(
					tabHoverBackgroundColor
				),
			}),
		},
	});

	const innerBlocksProps = useInnerBlocksProps.save({
		className: 'airo-wp-tabs__panels',
	});

	return (
		<div {...blockProps}>
			{/* Tab navigation will be generated by frontend JS from innerBlocks */}
			<div className="airo-wp-tabs__nav" role="tablist"></div>

			{/* Tab panels */}
			<div {...innerBlocksProps} />
		</div>
	);
}
